export const SIMULATION_CONFIG = {
  initial: { fame: 20, scrap: 0, threat: 20, rngSeed: 0x9e3779b9 },
  limits: { fame: 100, threat: 100, energy: 100 },
  sleep: {
    sleepAtEnergy: 20,
    wakeForOrderEnergy: 50,
  },
  goal: { fame: 50 },
  threat: { elevated: 35, severe: 50 },
  chance: {
    minimum: 5,
    maximum: 100,
    cleanupBase: 35,
    teamSkillMultiplier: 1.5,
    teamSkillBonusCap: 45,
    fatigueStartsBelowEnergy: 70,
    fatiguePenaltyEnergyStep: 5,
    fatiguePenaltyCap: 10,
    styleBonus: 10,
  },
  mission: {
    initialAvailableCount: 2,
    cleanupWork: 30,
    raidTriggerWork: 15,
    rewardScrap: 10,
    rewardFame: 5,
    energyCostPerBaseCleanup: 20,
    restPerSecond: 1,
    mapSpeed: 4,
    minimumTravelTime: 2,
    flowInterval: 35,
    flowCycle: [2, 5, 1, 4, 3],
    eventLogLimit: 20,
    templates: [
      { id: 'a', title: 'mission.a', x: 23, y: 25, priority: 1 },
      { id: 'b', title: 'mission.b', x: 75, y: 24, priority: 1 },
      { id: 'c', title: 'mission.c', x: 76, y: 70, priority: 1 },
      { id: 'd', title: 'mission.d', x: 22, y: 72, priority: 1 },
    ],
    generation: {
      highPriorityEvery: 3,
      highPriorityOffset: 2,
      normalPriority: 1,
      highPriority: 2,
      maxPlacementAttempts: 20,
      x: { minimum: 14, multiplier: 37, range: 72 },
      y: { minimum: 16, multiplier: 53, range: 65 },
      minimumSeparation: 18,
      fallback: { x: 50, y: 20 },
    },
  },
  raid: {
    successfulCleanupsBeforeTrigger: 2,
    supportTravelTime: 8,
    researchedSupportTravelTime: 5,
    supportBaseChance: 35,
    attackBaseChance: 20,
    injuryBaseChance: 60,
    minimumInjuryChance: 20,
    injuryRecoveryTime: 60,
    medkitRecoveryTime: 20,
  },
  research: {
    duration: 60,
    scrapCost: 20,
    scrapInterval: 3,
    energyCost: 5,
    minimumStartEnergy: 50,
    minimumContinueEnergy: 20,
    nodes: [
      { id: 'field_scanners', name: 'research.field_scanners.name', result: 'research.field_scanners.result', rewardItemId: 'scanner', rewardCount: 2 },
      { id: 'emergency_dispatch', name: 'research.emergency_dispatch.name', result: 'research.emergency_dispatch.result' },
      { id: 'improvised_defense', name: 'research.improvised_defense.name', result: 'research.improvised_defense.result', rewardItemId: 'nonlethal_weapon', rewardCount: 1 },
    ],
  },
  equipment: {
    items: [
      { id: 'armor_vest', name: 'item.armor_vest.name', slot: 'armor', initialCount: 2, effect: 'item.armor_vest.effect', injuryReduction: 10 },
      { id: 'toolkit', name: 'item.toolkit.name', slot: 'hands', initialCount: 1, effect: 'item.toolkit.effect', cleanupBonus: 12 },
      { id: 'headset', name: 'item.headset.name', slot: 'belt', initialCount: 1, effect: 'item.headset.effect', supportBonus: 15 },
      { id: 'medkit', name: 'item.medkit.name', slot: 'belt', initialCount: 1, effect: 'item.medkit.effect' },
      { id: 'scanner', name: 'item.scanner.name', slot: 'belt', initialCount: 0, effect: 'item.scanner.effect', cleanupBonus: 8 },
      { id: 'nonlethal_weapon', name: 'item.nonlethal_weapon.name', slot: 'hands', initialCount: 0, effect: 'item.nonlethal_weapon.effect', attackBonus: 25 },
    ],
  },
  story: {
    successfulCleanupsBeforeTrigger: 3,
    decisions: {
      shelter: { fame: 15, threat: 20 },
      interrogate: { fame: 10, threat: 0 },
      escort: { fame: 5, threat: 0 },
      exploit: { fame: 15, threat: 15 },
    },
  },
  map: { base: { x: 46, y: 51 } },
  cats: [
    { id: 'marlowe', name: 'cat.marlowe.name', role: 'cat.marlowe.role', energy: 88, reaction: 4, combat: 2, tech: 4, perception: 6, scouting: 5, cleanupTrait: 0, supportTrait: 5, attackTrait: 0, injuryTrait: 0 },
    { id: 'pixel', name: 'cat.pixel.name', role: 'cat.pixel.role', energy: 92, reaction: 5, combat: 2, tech: 9, perception: 5, scouting: 4, cleanupTrait: 5, supportTrait: 0, attackTrait: 0, injuryTrait: 0 },
    { id: 'rust', name: 'cat.rust.name', role: 'cat.rust.role', energy: 78, reaction: 5, combat: 5, tech: 8, perception: 4, scouting: 3, cleanupTrait: 5, supportTrait: 0, attackTrait: 0, injuryTrait: 0 },
    { id: 'shorokh', name: 'cat.shorokh.name', role: 'cat.shorokh.role', energy: 83, reaction: 7, combat: 3, tech: 4, perception: 10, scouting: 9, cleanupTrait: 0, supportTrait: 10, attackTrait: 0, injuryTrait: 0 },
    { id: 'bastion', name: 'cat.bastion.name', role: 'cat.bastion.role', energy: 95, reaction: 8, combat: 9, tech: 3, perception: 5, scouting: 3, cleanupTrait: 0, supportTrait: 0, attackTrait: 10, injuryTrait: 0 },
    { id: 'myata', name: 'cat.myata.name', role: 'cat.myata.role', energy: 86, reaction: 5, combat: 3, tech: 5, perception: 8, scouting: 6, cleanupTrait: 0, supportTrait: 0, attackTrait: 0, injuryTrait: 10 },
  ],
} as const
