export const SIMULATION_CONFIG = {
  initial: { fame: 20, scrap: 0, threat: 20, rngSeed: 0x9e3779b9 },
  mission: {
    cleanupDuration: 30,
    raidTriggerProgress: 15,
    rewardScrap: 10,
    rewardFame: 5,
    energyCost: 20,
    minimumDepartureEnergy: 50,
    restPerSecond: 1,
    mapSpeed: 4,
    minimumTravelTime: 2,
    flowInterval: 35,
    flowCycle: [2, 5, 1, 4, 3],
  },
  raid: {
    successfulCleanupsBeforeTrigger: 2,
    supportTravelTime: 8,
    researchedSupportTravelTime: 5,
    supportBaseChance: 35,
    attackBaseChance: 20,
    injuryBaseChance: 60,
    minimumInjuryChance: 20,
    injuryRecoveryTime: 60,
    medkitRecoveryTime: 20,
  },
  research: {
    duration: 60,
    scrapCost: 20,
    scrapInterval: 3,
    energyCost: 5,
    minimumStartEnergy: 50,
    minimumContinueEnergy: 20,
    nodes: [
      { id: 'field_scanners', name: 'Полевые сканеры', result: '2 сканера на складе', rewardItemId: 'scanner', rewardCount: 2 },
      { id: 'emergency_dispatch', name: 'Протокол экстренной диспетчеризации', result: 'Поддержка прибывает за 5 секунд' },
      { id: 'improvised_defense', name: 'Импровизированная защита', result: 'Нелетальное оружие и действие «Напасть»', rewardItemId: 'nonlethal_weapon', rewardCount: 1 },
    ],
  },
  equipment: {
    items: [
      { id: 'armor_vest', name: 'Бронежилет', slot: 'armor', initialCount: 2, effect: '−10 п.п. к вероятности ранения', injuryReduction: 10 },
      { id: 'toolkit', name: 'Инструментальный набор', slot: 'hands', initialCount: 1, effect: '+12 п.п. к уборке', cleanupBonus: 12 },
      { id: 'headset', name: 'Переговорная гарнитура', slot: 'belt', initialCount: 1, effect: '+15 п.п. к запросу поддержки', supportBonus: 15 },
      { id: 'medkit', name: 'Аптечка', slot: 'belt', initialCount: 1, effect: 'Лечение ранения за 20 секунд' },
      { id: 'scanner', name: 'Полевой сканер', slot: 'belt', initialCount: 0, effect: '+8 п.п. к уборке', cleanupBonus: 8 },
      { id: 'nonlethal_weapon', name: 'Нелетальное оружие', slot: 'hands', initialCount: 0, effect: '+25 п.п. к нападению', attackBonus: 25 },
    ],
  },
  story: {
    successfulCleanupsBeforeTrigger: 3,
    decisions: {
      shelter: { fame: 15, threat: 20 },
      interrogate: { fame: 10, threat: 0 },
      escort: { fame: 5, threat: 0 },
      exploit: { fame: 15, threat: 15 },
    },
  },
  map: { base: { x: 46, y: 51 } },
  cats: [
    { id: 'marlowe', name: 'Марлоу', role: 'переговорщик', energy: 88, reaction: 4, combat: 2, tech: 4, perception: 6, scouting: 5, cleanupTrait: 0, supportTrait: 5, attackTrait: 0, injuryTrait: 0 },
    { id: 'pixel', name: 'Пиксель', role: 'техник', energy: 92, reaction: 5, combat: 2, tech: 9, perception: 5, scouting: 4, cleanupTrait: 5, supportTrait: 0, attackTrait: 0, injuryTrait: 0 },
    { id: 'rust', name: 'Ржа', role: 'грузчик', energy: 78, reaction: 5, combat: 5, tech: 8, perception: 4, scouting: 3, cleanupTrait: 5, supportTrait: 0, attackTrait: 0, injuryTrait: 0 },
    { id: 'shorokh', name: 'Шорох', role: 'разведчик', energy: 83, reaction: 7, combat: 3, tech: 4, perception: 10, scouting: 9, cleanupTrait: 0, supportTrait: 10, attackTrait: 0, injuryTrait: 0 },
    { id: 'bastion', name: 'Бастион', role: 'защитник', energy: 95, reaction: 8, combat: 9, tech: 3, perception: 5, scouting: 3, cleanupTrait: 0, supportTrait: 0, attackTrait: 10, injuryTrait: 0 },
    { id: 'myata', name: 'Мята', role: 'медик', energy: 86, reaction: 5, combat: 3, tech: 5, perception: 8, scouting: 6, cleanupTrait: 0, supportTrait: 0, attackTrait: 0, injuryTrait: 10 },
  ],
} as const
