export type Speed = 0 | 1 | 5 | 10
export type Cat = { id:string; name:string; role:string; energy:number; tech:number; perception:number; assignedTo?:string }
export type Mission = { id:string; title:string; x:number; y:number; priority:number; status:'available'|'assigned'; squadId?:string }
export type Phase = 'base'|'outbound'|'cleanup'|'returning'
export type Squad = { id:string; name:string; members:string[]; phase:Phase; travel:number; travelDuration:number; progress:number; completed:number; missionId?:string; target?:Pick<Mission,'id'|'title'|'x'|'y'|'priority'> }
export type State = { fame:number; scrap:number; threat:number; speed:Speed; time:number; activeView:'map'|'base'; cats:Cat[]; squads:Squad[]; missions:Mission[]; missionSerial:number; log:string[] }
const cats:Cat[]=[{id:'marlowe',name:'Марлоу',role:'переговорщик',energy:88,tech:4,perception:6},{id:'pixel',name:'Пиксель',role:'техник',energy:92,tech:9,perception:5},{id:'rust',name:'Ржа',role:'грузчик',energy:78,tech:8,perception:4},{id:'shorokh',name:'Шорох',role:'разведчик',energy:83,tech:4,perception:10},{id:'bastion',name:'Бастион',role:'защитник',energy:95,tech:3,perception:5},{id:'myata',name:'Мята',role:'медик',energy:86,tech:5,perception:8}]
const templates:Mission[]=[{id:'a',title:'Свалка у эстакады',x:23,y:25,priority:1,status:'available'},{id:'b',title:'Складской квартал',x:75,y:24,priority:1,status:'available'},{id:'c',title:'Ржавый терминал',x:76,y:70,priority:1,status:'available'},{id:'d',title:'Старый коллектор',x:22,y:72,priority:1,status:'available'}]
const base={x:46,y:51}, mapSpeed=4
export function createState():State{return{fame:20,scrap:0,threat:20,speed:0,time:0,activeView:'map',cats:structuredClone(cats),missions:structuredClone(templates.slice(0,2)),missionSerial:0,squads:[{id:'alpha',name:'Отряд «Альфа»',members:[],phase:'base',travel:0,travelDuration:0,progress:0,completed:0},{id:'bravo',name:'Отряд «Браво»',members:[],phase:'base',travel:0,travelDuration:0,progress:0,completed:0}],log:['09:00 · База NINE LIVES CORP готова к работе']}}
function note(s:State,text:string){s.log=[`${clock(s.time)} · ${text}`,...s.log].slice(0,20)} function clock(t:number){const m=540+Math.floor(t/60);return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
export function assignCat(state:State,catId:string,squadId:string){const cat=state.cats.find(c=>c.id===catId),squad=state.squads.find(s=>s.id===squadId);if(!cat||!squad||squad.phase!=='base')return;state.squads.forEach(s=>s.members=s.members.filter(id=>id!==catId));squad.members.push(catId);cat.assignedTo=squadId;note(state,`${cat.name} назначен в ${squad.name}`)}
function distanceFromBase(m:Pick<Mission,'x'|'y'>){return Math.hypot(m.x-base.x,m.y-base.y)}
function travelTime(m:Pick<Mission,'x'|'y'>){return Math.max(2,distanceFromBase(m)/mapSpeed)}
function start(state:State,s:Squad){const m=state.missions.filter(m=>m.status==='available').sort((a,b)=>b.priority-a.priority||distanceFromBase(a)-distanceFromBase(b))[0];if(!m)return;m.status='assigned';m.squadId=s.id;s.missionId=m.id;s.target={id:m.id,title:m.title,x:m.x,y:m.y,priority:m.priority};s.phase='outbound';s.travel=0;s.travelDuration=travelTime(m);note(state,`${s.name} выехал: ${m.title}`)}
function finish(state:State,s:Squad){s.completed++;state.scrap+=10;state.fame=Math.min(100,state.fame+5);s.members.forEach(id=>{const c=state.cats.find(c=>c.id===id)!;c.energy=Math.max(0,c.energy-20)});s.phase='returning';s.travel=0;s.progress=0;note(state,`${s.name} закончил уборку: +10 лома, +5 известности`)}
function spawnMission(state:State):Mission { const label=templates[state.missionSerial%templates.length].title; const priority=state.missionSerial%3===2?2:1; for(let attempt=0;attempt<20;attempt++){const n=++state.missionSerial;const x=14+(n*37)%72;const y=16+(n*53)%65;const clear=state.missions.every(m=>Math.hypot(m.x-x,m.y-y)>18);if(clear)return{id:`cleanup-${n}`,title:label,x,y,priority,status:'available'}} const n=++state.missionSerial;return{id:`cleanup-${n}`,title:label,x:50,y:20,priority,status:'available'} }
function desiredMissionCount(time:number){return[2,5,1,4,3][Math.floor(time/35)%5]}
function reconcileMissionFlow(state:State){const desired=desiredMissionCount(state.time);while(state.missions.length<desired)state.missions.push(spawnMission(state));while(state.missions.length>desired){const mission=state.missions.find(m=>m.status==='available');if(!mission)break;state.missions.splice(state.missions.indexOf(mission),1)}}
export function tick(state:State,seconds:number){if(!state.speed)return;const e=seconds*state.speed;state.time+=e;reconcileMissionFlow(state);state.cats.forEach(c=>{const s=state.squads.find(s=>s.id===c.assignedTo);if(!s||s.phase==='base')c.energy=Math.min(100,c.energy+e)});state.squads.forEach(s=>{if(s.phase==='base'){if(s.members.length&&s.members.every(id=>state.cats.find(c=>c.id===id)!.energy>=50))start(state,s);return}if(s.phase==='outbound'||s.phase==='returning'){s.travel+=e;if(s.travel>=s.travelDuration){if(s.phase==='outbound'){s.phase='cleanup';s.progress=0;note(state,`${s.name} прибыл на место уборки`)}else{const m=state.missions.find(m=>m.id===s.missionId);if(m)state.missions.splice(state.missions.indexOf(m),1);s.phase='base';s.missionId=undefined;s.target=undefined;s.travel=0;s.travelDuration=0;note(state,`${s.name} вернулся на базу`)}}return}s.progress+=e;if(s.progress>=30)finish(state,s)})}
