<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive } from 'vue'
import { assignCat, createState, tick, type Speed, type Squad } from './core/simulation'
const state = reactive(createState()); let timer: number
onMounted(() => timer = window.setInterval(() => tick(state, .25), 250)); onUnmounted(() => clearInterval(timer))
const totalRuns = computed(() => state.squads.reduce((n, s) => n + s.completed, 0))
const fmtTime = computed(() => `${String(9 + Math.floor(state.time / 3600)).padStart(2, '0')}:${String(Math.floor(state.time / 60) % 60).padStart(2, '0')}`)
function setSpeed(speed: Speed) { state.speed = speed }
function squadStyle(s: Squad) { const target = s.target, base = { x: 46, y: 51 }, duration = s.travelDuration || 1; if (!target || s.phase === 'base') return { left: `${base.x}%`, top: `${base.y}%`, opacity: 0 }; const r = s.phase === 'outbound' ? Math.min(1, s.travel / duration) : s.phase === 'returning' ? 1 - Math.min(1, s.travel / duration) : 1; return { left: `${base.x + (target.x - base.x) * r}%`, top: `${base.y + (target.y - base.y) * r}%` } }
function label(s: Squad) { return s.phase === 'base' ? (s.members.length ? 'На базе / готов' : 'Нет состава') : s.phase === 'outbound' ? `Выезд · ${s.target?.title} (${Math.ceil(s.travelDuration)} с)` : s.phase === 'returning' ? 'Возвращается на базу' : `Уборка · ${Math.round(s.progress / 30 * 100)}%` }
</script>
<template>
  <main>
    <header class="topbar"><div class="brand">NINE <i>LIVES</i><small>CORP / OPERATIONS</small></div><div class="metrics"><span>ИЗВЕСТНОСТЬ <b>{{ state.fame }}</b><em>/ 50</em></span><span>ЛОМ <b>{{ state.scrap }}</b></span><span>ВРЕМЯ <b>{{ fmtTime }}</b></span></div><nav><button :class="{active: state.activeView === 'map'}" @click="state.activeView = 'map'">Карта</button><button :class="{active: state.activeView === 'base'}" @click="state.activeView = 'base'">База</button></nav><div class="speed"><button v-for="x in [0,1,5,10] as Speed[]" :class="{active: state.speed === x}" @click="setSpeed(x)">{{ x ? `×${x}` : 'Ⅱ' }}</button></div></header>
    <section v-if="state.activeView === 'map'" class="map-view"><div class="map-grid"><div class="district d1">Старый сектор</div><div class="district d2">Промзона</div><div class="district d3">Терминал</div><div class="base-pin"><strong>NL</strong><span>БАЗА</span></div><div v-for="m in state.missions.filter(m => m.status === 'available')" :key="m.id" class="cleanup-pin" :style="{left: `${m.x}%`, top: `${m.y}%`}"><span>♜</span><b>УБОРКА</b><small>{{ m.title }}</small></div><div v-for="s in state.squads.filter(s => s.target)" :key="`target-${s.id}`" class="cleanup-pin assigned" :style="{left: `${s.target!.x}%`, top: `${s.target!.y}%`}"><span>♜</span><b>УБОРКА</b><small>{{ s.target!.title }}</small></div><div v-for="s in state.squads" :key="s.id" class="squad-marker" :class="s.phase" :style="squadStyle(s)"><span v-for="member in s.members" :key="member" class="cat-silhouette">♟</span><b>{{ s.name }}</b><small>{{ label(s) }}</small></div></div><aside><h2>ОПЕРАТИВНАЯ ЛЕНТА</h2><p class="goal">Цель: 50 известности и закрытое расследование.</p><article v-for="item in state.log" :key="item">{{ item }}</article></aside></section>
    <section v-else class="base-view"><div class="cutaway"><div class="room lab">ЛАБОРАТОРИЯ<br><small>Исследования — следующий этап</small></div><div class="room control">ДИСПЕТЧЕРСКАЯ<br><small>{{ totalRuns }} заверш. уборок</small></div><div class="room garage">ГАРАЖ<br><small>2 отряда на готовности</small></div></div><aside class="roster"><h2>СОСТАВ И ОТРЯДЫ</h2><div v-for="cat in state.cats" :key="cat.id" class="cat"><img :src="`/assets/art/portrait-${cat.id}-v1.png`" :alt="cat.name"><div><b>{{ cat.name }}</b><small>{{ cat.role }} · энергия {{ Math.round(cat.energy) }}%</small></div><select :value="cat.assignedTo || ''" @change="assignCat(state, cat.id, ($event.target as HTMLSelectElement).value)"><option value="">не назначен</option><option v-for="s in state.squads" :value="s.id">{{ s.name }}</option></select></div><div v-for="s in state.squads" :key="s.id" class="squad-status"><b>{{ s.name }}</b><span>{{ s.members.length }} кот. · {{ s.phase === 'base' ? 'на базе' : 'в поле' }}</span></div></aside></section>
  </main>
</template>
