export const SIMULATION_CONFIG = {
  initial: { fame: 20, scrap: 0, corporateThreat: 20, rngSeed: 0x9e3779b9 },
  limits: { fame: 100, corporateThreat: 100, energy: 100 },
  sleep: {
    sleepAtEnergy: 20,
    wakeForOrderEnergy: 50,
  },
  goal: { fame: 50 },
  threat: { elevated: 35, severe: 50 },
  chance: {
    minimum: 5,
    maximum: 100,
    cleanupBase: 35,
    teamSkillMultiplier: 1.5,
    teamSkillBonusCap: 45,
    fatigueStartsBelowEnergy: 70,
    fatiguePenaltyEnergyStep: 5,
    fatiguePenaltyCap: 10,
    styleBonus: 10,
  },
  mission: {
    initialAvailableCount: 0,
    cleanupWork: 30,
    raidTriggerWork: 15,
    rewardScrap: 10,
    rewardFame: 5,
    energyCostPerBaseCleanup: 20,
    energyCostPerTravelSecond: 1,
    restPerSecond: 1,
    mapSpeed: 4,
    minimumTravelTime: 2,
    flowInterval: 35,
    flowCycle: [2, 5, 1, 4, 3],
    eventLogLimit: 20,
    templates: [
      { id: 'a', title: 'mission.a', x: 23, y: 25, priority: 1 },
      { id: 'b', title: 'mission.b', x: 75, y: 24, priority: 1 },
      { id: 'c', title: 'mission.c', x: 76, y: 70, priority: 1 },
      { id: 'd', title: 'mission.d', x: 22, y: 72, priority: 1 },
    ],
    generation: {
      highPriorityEvery: 3,
      highPriorityOffset: 2,
      normalPriority: 1,
      highPriority: 2,
      maxPlacementAttempts: 20,
      x: { minimum: 14, multiplier: 37, range: 72 },
      y: { minimum: 16, multiplier: 53, range: 65 },
      minimumSeparation: 18,
      fallback: { x: 50, y: 20 },
    },
  },
  raid: {
    successfulCleanupsBeforeTrigger: 2,
    supportTravelTime: 8,
    researchedSupportTravelTime: 5,
    supportBaseChance: 35,
    attackBaseChance: 20,
    injuryBaseChance: 60,
    minimumInjuryChance: 20,
    injuryRecoveryTime: 60,
    medkitRecoveryTime: 20,
    contactThreatRolls: { harmlessBelow: 30, armedBelow: 85 },
    checks: { observe: 20, recon: 10, scan: 15, contact: 15 },
    monolith: { travelTime: 12, initialTrust: 70, minimumResponseChance: 10, heavyTrust: 5, armedTrust: -10, harmlessTrust: -20 },
    police: { fastTravelTime: 8, delayedTravelTime: 12, slowTravelTime: 16 },
  },
  research: {
    duration: 60,
    scrapCost: 20,
    scrapInterval: 3,
    energyCost: 5,
    minimumStartEnergy: 50,
    minimumContinueEnergy: 20,
    nodes: [
      { id: 'field_scanners', name: 'research.field_scanners.name', result: 'research.field_scanners.result', rewardItemId: 'scanner', rewardCount: 2 },
      { id: 'emergency_dispatch', name: 'research.emergency_dispatch.name', result: 'research.emergency_dispatch.result' },
      { id: 'improvised_defense', name: 'research.improvised_defense.name', result: 'research.improvised_defense.result', rewardItemId: 'nonlethal_weapon', rewardCount: 1 },
    ],
  },
  equipment: {
    items: [
      { id: 'armor_vest', name: 'item.armor_vest.name', slot: 'armor', initialCount: 2, effect: 'item.armor_vest.effect', injuryReduction: 10 },
      { id: 'toolkit', name: 'item.toolkit.name', slot: 'hands', initialCount: 1, effect: 'item.toolkit.effect', cleanupBonus: 12 },
      { id: 'headset', name: 'item.headset.name', slot: 'belt', initialCount: 1, effect: 'item.headset.effect', supportBonus: 15 },
      { id: 'medkit', name: 'item.medkit.name', slot: 'belt', initialCount: 1, effect: 'item.medkit.effect' },
      { id: 'scanner', name: 'item.scanner.name', slot: 'belt', initialCount: 0, effect: 'item.scanner.effect', cleanupBonus: 8 },
      { id: 'nonlethal_weapon', name: 'item.nonlethal_weapon.name', slot: 'hands', initialCount: 0, effect: 'item.nonlethal_weapon.effect', attackBonus: 25 },
    ],
  },
  story: {
    successfulCleanupsBeforeTrigger: 3,
    signalDeadline: 60,
    arrivalDeadline: 60,
    verificationDuration: 30,
    deescalationDuration: 15,
    deescalationShelterThreatReduction: 5,
    unansweredThreat: 5,
    pursuedThreat: 5,
    myataLowEnergyThreshold: 30,
    bastionInterventionThreat: 5,
    shorokhFalseAlarmDelay: 20,
    observerOffset: { x: 12, y: -8 },
    aftermath: {
      defaultDelay: 60,
      interrogationDelay: 75,
      borderPoint: { x: 10, y: 78 },
      interceptPoint: { x: 62, y: 18 },
      falseEntrancePoint: { x: 82, y: 42 },
    },
    decisions: {
      shelter: { fame: 15, threat: 20 },
      interrogate: { fame: 10, threat: 0 },
      escort: { fame: 5, threat: 0 },
      exploit: { fame: 15, threat: 15 },
    },
  },
  urgentOperations: {
    waterFilters: {
      x: 55,
      y: 58,
      appearanceDelay: 15,
      assignmentDeadline: 75,
      specialistWorkDuration: 20,
      standardWorkDuration: 35,
      fullRewardFame: 5,
      fullRewardScrap: 10,
      partialRewardFame: 2,
      partialRewardScrap: 5,
    },
  },
  firstShift: {
    monolithDeadline: 120,
    containerDeadline: 90,
    residentialDutyDeadline: 90,
    southNodeDeadline: 90,
    container: {
      police_handoff: { policeRelation: 10, monolithRelation: 0, districtRisk: 15, warningDelay: 15, sample: false },
      independent_sample: { policeRelation: -5, monolithRelation: 0, districtRisk: 20, warningDelay: 0, sample: true },
      call_monolith: { policeRelation: -15, monolithRelation: -10, districtRisk: 25, warningDelay: 30, sample: false },
      ignore: { policeRelation: -15, monolithRelation: 0, districtRisk: 30, warningDelay: 45, sample: false },
    },
    residentialDuty: { x: 78, y: 31, riskSuccess: -5, riskFailure: 10 },
  },
  factions: {
    needleFront: {
      initialRelation: 20,
      maximumRelation: 50,
      exactHqDiscoveryRelation: -10,
      decisions: { shelter: -5, interrogate: -10, escort: -5, exploit: -15 },
    },
  },
  map: { base: { x: 46, y: 51 }, monolith: { x: 48, y: 14 }, police: { x: 75, y: 25 }, hedgehogDepot: { x: 83, y: 17 } },
  cats: [
    { id: 'marlowe', name: 'cat.marlowe.name', role: 'cat.marlowe.role', energy: 88, reaction: 4, combat: 2, tech: 4, perception: 6, scouting: 5, cleanupTrait: 0, supportTrait: 5, attackTrait: 0, injuryTrait: 0 },
    { id: 'pixel', name: 'cat.pixel.name', role: 'cat.pixel.role', energy: 92, reaction: 5, combat: 2, tech: 9, perception: 5, scouting: 4, cleanupTrait: 5, supportTrait: 0, attackTrait: 0, injuryTrait: 0 },
    { id: 'rust', name: 'cat.rust.name', role: 'cat.rust.role', energy: 78, reaction: 5, combat: 5, tech: 8, perception: 4, scouting: 3, cleanupTrait: 5, supportTrait: 0, attackTrait: 0, injuryTrait: 0 },
    { id: 'shorokh', name: 'cat.shorokh.name', role: 'cat.shorokh.role', energy: 83, reaction: 7, combat: 3, tech: 4, perception: 10, scouting: 9, cleanupTrait: 0, supportTrait: 10, attackTrait: 0, injuryTrait: 0 },
    { id: 'bastion', name: 'cat.bastion.name', role: 'cat.bastion.role', energy: 95, reaction: 8, combat: 9, tech: 3, perception: 5, scouting: 3, cleanupTrait: 0, supportTrait: 0, attackTrait: 10, injuryTrait: 0 },
    { id: 'myata', name: 'cat.myata.name', role: 'cat.myata.role', energy: 86, reaction: 5, combat: 3, tech: 5, perception: 8, scouting: 6, cleanupTrait: 0, supportTrait: 0, attackTrait: 0, injuryTrait: 10 },
  ],
} as const
